# Percentages and Averages

This notebook will calculate the percentages and averages of the data.

In [1]:
import pandas as pd
dataframe = pd.read_csv('./Testing transcribed into CSV.csv')
dataframe

,File,ID,Issues,Length,Verbosity,Success,Loading Time,Delta from Objective Time
0,1 (Technical Report - 37 pages),1-1-0,3,3.0,NaN,0.0,9168,6668
1,1 (Technical Report - 37 pages),1-1-1,1,10.0,0.0,0.5,70539,68039
2,1 (Technical Report - 37 pages),1-1-2,4,5.0,0.0,1.0,66267,63767
3,1 (Technical Report - 37 pages),1-1-3,3,20.0,NaN,0.0,88116,85616
4,1 (Technical Report - 37 pages),1-1-4,1,5.0,NaN,0.5,67013,64513
5,1 (Technical Report - 37 pages),1-2-0,1,5.0,NaN,0.5,39748,37248
6,1 (Technical Report - 37 pages),1-2-1,2,5.0,NaN,0.5,79262,76762
7,2 (Revision Notes - 41 pages),2-1-0,"5,1",10.0,1.0,0.5,92357,89857
8,2 (Revision Notes - 41 pages),2-1-1,2,15.0,1.0,0.5,146416,143916
9,2 (Revision Notes - 41 pages),2-1-2,2,NaN,1.0,0.5,139163,136663
10,2 (Revision Notes - 41 pages),2-1-3,2,5.0,1.0,1.0,71312,68812
11,2 (Revision Notes - 41 pages),2-1-4,1,5.0,0.0,0.5,58523,56023
12,2 (Revision Notes - 41 pages),2-2-0,"2,3",31.0,0.0,0.5,134752,132252
13,2 (Revision Notes - 41 pages),2-2-1,1,3.0,0.0,0.5,53696,51196
14,3 (Academic Paper - 6 pages),3-1-0,3,11.0,0.0,0.0,67954,65454
15,3 (Academic Paper - 6 pages),3-1-1,6,15.0,0.0,0.0,145082,142582
16,3 (Academic Paper - 6 pages),3-1-2,6,10.0,1.0,0.0,149169,146669
17,3 (Academic Paper - 6 pages),3-1-3,0,5.0,0.0,1.0,94402,91902
18,3 (Academic Paper - 6 pages),3-1-4,0,5.0,0.0,1.0,96726,94226
19,3 (Academic Paper - 6 pages),3-2-0,1,10.0,1.0,0.5,120205,117705
20,3 (Academic Paper - 6 pages),3-2-1,6,15.0,1.0,0.0,344908,342408

## Average Success Rate

In [ ]:
Average_Success_Rate = dataframe.loc[:, 'Success'].mean()
Percentage = Average_Success_Rate * 100
print(f"{Average_Success_Rate:.2%} (2 d.p.)")

0.4523809523809524
45.24% (2 d.p.)